services:
  printmaker:
    build:
      dockerfile: blender.Dockerfile
      context: .
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    env_file:
      - .env
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud